from warmup import crack_caesar

def test_a():
    assert crack_caesar("SJSFM ROM WG HCACFFCK'G SJS") == "EVERY DAY IS TOMORROW'S EVE"

def test_b():
    assert (crack_caesar("JCRAT WTCGN PCS PJCI TB WPS P QXV QTS XC DCT RDGCTG, PCS SDGDIWN P AXIIAT QTS XC PCDIWTG RDGCTG. IWTGT LPH CD VPGGTI PI PAA, PCS CD RTAAPG TMRTEI P HBPAA WDAT RPAATS P RNRADCT RTAAPG.")
            == "UNCLE HENRY AND AUNT EM HAD A BIG BED IN ONE CORNER, AND DOROTHY A LITTLE BED IN ANOTHER CORNER. THERE WAS NO GARRET AT ALL, AND NO CELLAR EXCEPT A SMALL HOLE CALLED A CYCLONE CELLAR.")
    
def test_c():
    assert (crack_caesar("MQBPMZ BPM EMTT EIA DMZG LMMX, WZ APM NMTT DMZG ATWETG, NWZ APM PIL XTMVBG WN BQUM, IA APM EMVB LWEV, BW TWWS IJWCB PMZ.")
            == "EITHER THE WELL WAS VERY DEEP, OR SHE FELL VERY SLOWLY, FOR SHE HAD PLENTY OF TIME, AS SHE WENT DOWN, TO LOOK ABOUT HER.")
        
def test_d():
    assert (crack_caesar("BUT SHE BORE IT ALL LIKE A GOOD PATIENT QUEEN AS SHE WAS.") ==
            "BUT SHE BORE IT ALL LIKE A GOOD PATIENT QUEEN AS SHE WAS.")